"""Removed the incorrect composite unique constraint from linked_accounts

Revision ID: edf37a9585fd
Revises: 2b093eed3b45
Create Date: 2025-09-16 11:48:24.866448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf37a9585fd'
down_revision: Union[str, None] = '2b093eed3b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linked_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_provider', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linked_accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_provider', ['user_id', 'provider_name'])
    # ### end Alembic commands ###
